WMSURFIDSYS/Controllers/CollegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using System.Net;

namespace WMSURFIDSYS.Controllers
{
    public class CollegeController : Controller
    {
        // GET: College
        public ActionResult Index()
        {
            var db = DAL.DbContext.Create();

            IEnumerable<DAL.College> colleges = db.Colleges.All().ToList();

            colleges = colleges.OrderBy(c => c.CollegeName);

            return View(colleges.ToList());
        }

        // GET: Course/Details/5
        public ActionResult Details(int id)
        {
            var db = DAL.DbContext.Create();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College colleges = db.Colleges.Get(id);
            if (colleges == null)
            {
                return HttpNotFound();
            }
            return View(colleges);
        }

        // GET: Course/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CollegeID,CollegeName,CollegeAbbv")] College college)
        {
            var db = DAL.DbContext.Create();
            if (ModelState.IsValid)
            {
                var collegeId = db.Colleges.Insert(college);

                if (collegeId.HasValue && collegeId.Value > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }

            return View(college);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int id)
        {
            var db = DAL.DbContext.Create();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Get(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(College college, int id)
        {
            var db = DAL.DbContext.Create();
            if (ModelState.IsValid)
            {
                db.Colleges.Update(college.Id, college);
                
                return RedirectToAction("Index");
            }

            return View(college);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int id)
        {
            var db = DAL.DbContext.Create();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Get(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var db = DAL.DbContext.Create();
            College college = db.Colleges.Get(id);
            bool IsDeleted = db.Colleges.Delete(id);
            if (IsDeleted)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            var db = DAL.DbContext.Create();
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WMSURFIDSYS/Controllers/CourseController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace WMSURFIDSYS.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Index()
        {
            var db = DAL.DbContext.Create();

            return View(db.GetCourses());
        }

        // GET: Course/Details/5
        public ActionResult Details(int id)
        {
            var db = DAL.DbContext.Create();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Course/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,CourseName,CourseAbbv")] Course course)
        {
            var db = DAL.DbContext.Create();
            if (ModelState.IsValid)
            {
                var courseId = db.Courses.Insert(course);

                if (courseId.HasValue && courseId.Value > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }

            return View(course);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int id)
        {
            var db = DAL.DbContext.Create();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Course course)
        {
            var db = DAL.DbContext.Create();
            if (ModelState.IsValid)
            {
                db.UpdateCourse(course);
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int id)
        {
            var db = DAL.DbContext.Create();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var db = DAL.DbContext.Create();
            Course course = db.Courses.Get(id);
            bool IsDeleted = db.Courses.Delete(id);
            if (IsDeleted)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }

        protected override void Dispose(bool disposing)
        {
            var db = DAL.DbContext.Create();
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WMSURFIDSYS/Controllers/TapLogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WMSURFIDSYS.ViewModel;

namespace WMSURFIDSYS.Controllers
{
    public class TapLogController : Controller
    {
        // GET: TapLog
        public ActionResult Index(string searchString)
        {
            var db = DAL.DbContext.Create();

            IEnumerable<DAL.TapLog> taplogs = db.TapLogs.All().ToList();
            taplogs = taplogs.OrderByDescending(t => t.DateTimeTap);

            int studentId;
            int.TryParse(searchString, out studentId);

            if (!String.IsNullOrEmpty(searchString))
            {
                taplogs = db.SelectStudent(studentId, searchString, searchString);
            }

            foreach (var taplog in taplogs)
            {
                taplog.Student = db.Students.Get(taplog.StudentID);
                taplog.Student.Course = db.Courses.Get(taplog.Student.CourseID);
            }

            return View(taplogs.ToList());
        }


        public ActionResult ExportToExcel(DateTime? fromDate, DateTime? toDate)
        {
            var db = DAL.DbContext.Create();

            GridView gv = new GridView();

            ExportToExcelData exportToExcelData = new ExportToExcelData();

            var confromDate = Convert.ToDateTime(fromDate);
            var contoDate = Convert.ToDateTime(toDate);

            var addToDate = contoDate.AddDays(1);

            var taplogs = db.SelectStudentsDateTap(confromDate, addToDate);
            List<ExportToExcel> list = new List<ExportToExcel>();
            foreach (var taplog in taplogs)
            {
                taplog.Student = db.Students.Get(taplog.StudentID);
                taplog.Student.Course = db.Courses.Get(taplog.Student.CourseID);

                list.Add(new ExportToExcel
                {
                    DateTimeTap = taplog.DateTimeTap,
                    StudentID = taplog.Student.StudentID,
                    LastName = taplog.Student.LastName,
                    FirstName = taplog.Student.FirstName,
                    CourseAbbv = taplog.Student.Course.CourseAbbv
                });
            }

            gv.DataSource = list.ToList();
            gv.DataBind();
            Response.Clear();
            Response.Buffer = true;
            Response.ContentType = "application/ms-excel";
            Response.AddHeader("content-disposition", "attachment;filename=StudentTapLogList.xls");
            Response.Charset = "";

            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);

            gv.RenderControl(htw);

            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();

            return RedirectToAction("Index");
            //return View(list.ToList());
        }


        public ActionResult SearchByDate(DateTime? fromDate, DateTime? toDate)
        {
            var db = DAL.DbContext.Create();

            IEnumerable<DAL.TapLog> taplogs = db.TapLogs.All().ToList();
            taplogs = taplogs.OrderByDescending(t => t.DateTimeTap);

            if (!fromDate.HasValue) fromDate = DateTime.Now.Date;
            if (!toDate.HasValue) toDate = fromDate.GetValueOrDefault(DateTime.Now.Date).Date.AddDays(1);
            if (toDate < fromDate) toDate = fromDate.GetValueOrDefault(DateTime.Now.Date).Date.AddDays(1);
            ViewBag.fromDate = fromDate;
            ViewBag.toDate = toDate;

            var confromDate = Convert.ToDateTime(fromDate);
            var contoDate = Convert.ToDateTime(toDate);

            var addToDate = contoDate.AddDays(1);

            taplogs = db.SelectStudentsDateTap(confromDate, addToDate);

            foreach (var taplog in taplogs)
            {
                taplog.Student = db.Students.Get(taplog.StudentID);
                taplog.Student.Course = db.Courses.Get(taplog.Student.CourseID);
            }

            return View(taplogs.ToList());
        }

    }
}

WMSURFIDSYS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Western Mindanao State University</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript">
    $(document).ready(function () {
        $(".DatePicker").datepicker({
            dateFormat: 'dd M yy',
            changeMonth: true,
            changeYear: true,
        });
    });
    </script>

</head>
<body>
    <div class="container">
        <div class="masthead">
            <h3 class="text-muted">@Html.ActionLink("WMSURFIDSYS", "Index", "Home")</h3>
            <ul class="nav nav-justified">

                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                    <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Colleges", "Index", "College")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Course")</li>           
                    <li>@Html.ActionLink("TagTapLogs", "Index", "TapLog")</li>
                            @*<li>@Html.ActionLink("Custom Filter", "Index", "Student/Filter")</li>
                            <li>@Html.ActionLink("Students not Enrolled", "Index", "unEnrolledStudents")</li>
                            <li>@Html.ActionLink("Student with Message", "Index", "Messages")</li>*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("School Year", "Index", "schoolyear")</li>
                            <li>@Html.ActionLink("Semester", "Index", "semester")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("SemSchoolYear", "Index", "SemSchoolYear")</li>
                        </ul>
                    </li>
                }

                @if (Request.IsAuthenticated && User.IsInRole("UPress"))
                {
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                }

                @if (Request.IsAuthenticated && User.IsInRole("MISTO"))
                {
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Western Mindanao State University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>