WMSURFIDSYS/Controllers/SemesterController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace WMSURFIDSYS.Controllers
{
    public class SemesterController : Controller
    {
        // GET: Semester
        public ActionResult Index()
        {
            var db = DAL.DbContext.Create();

            return View(db.Semesters.All());
        }

        // GET: Sem/Details/5
        public ActionResult Details(int id)
        {
            var db = DAL.DbContext.Create();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Semester semester = db.Semesters.Get(id);

            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        // GET: Sem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SemesterID,SemesterName")] Semester semester)
        {
            var db = DAL.DbContext.Create();

            if (ModelState.IsValid)
            {
                db.Semesters.Insert(semester);
                return RedirectToAction("Index");
            }

            return View(semester);
        }

        // GET: Sem/Edit/5
        public ActionResult Edit(int id)
        {
            var db = DAL.DbContext.Create();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Semester semester = db.Semesters.Get(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        // POST: Sem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Semester semester)
        {
            var db = DAL.DbContext.Create();

            if (ModelState.IsValid)
            {
                db.UpdateSemester(semester);
                return RedirectToAction("Index");
            }
            return View(semester);
        }

        // GET: Sem/Delete/5
        public ActionResult Delete(int id)
        {
            var db = DAL.DbContext.Create();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Semester semester = db.Semesters.Get(id);

            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        // POST: Sem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Semester semester)
        {
            var db = DAL.DbContext.Create();

            Semester sem = db.Semesters.Get(semester.Id);
            try
            {
                bool IsDeleted = db.DeleteSemester(semester);
                if (IsDeleted)
                {
                    ModelState.AddModelError("", "Unable to delete semester due to dependencies. Make semester is not currenlty in used.");

                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception dex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { semester, saveChangesError = true });
            }
            return View(sem);
        }

        protected override void Dispose(bool disposing)
        {
            var db = DAL.DbContext.Create();

            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WMSURFIDSYS/Views/Semester/Create.cshtml
@model DAL.Semester

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Semester</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SemesterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemesterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SemesterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMSURFIDSYS/Views/Semester/Delete.cshtml
@model DAL.Semester

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Semester</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SemesterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemesterName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.Id)
        @Html.ValidationMessageFor(model => model.SemesterName, "", new { @class = "text-danger" })

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |


            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WMSURFIDSYS/Views/Semester/Details.cshtml
@model DAL.Semester

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Semester</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SemesterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemesterName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WMSURFIDSYS/Views/Semester/Edit.cshtml
@model DAL.Semester

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Semester", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Semester</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemesterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SemesterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMSURFIDSYS/Views/Semester/Index.cshtml
@model IEnumerable<DAL.Semester>

@{
    ViewBag.Title = "Index";
}

<h2>Semester</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SemesterName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SemesterName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>